# Documentation: https://github.com/JuliaCI/Appveyor.jl
environment:
  matrix:
    - julia_version: 1.0
    - julia_version: 1.8
    - julia_version: nightly
  COVERALLS_TOKEN:
    secure: Oko5xlmGvguMWp0Ymt3rxm4PtrUh9ptYVfl1h2IIBdwrbYh7TUUWBO8wRl1Yik1E
platform:
  - x64
cache:
  - '%USERPROFILE%\.julia\artifacts'
matrix:
  allow_failures:
    - julia_version: nightly
branches:
  only:
    - main
    - /release-.*/
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e 'Pkg.test("BicycleEfficiency", coverage=true)'
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
after_test:
  - C:\projects\julia\bin\julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(process_folder())"
